name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install coverage 
        pip install .
    - name: Run coverage
      run: |
        coverage run --source strong_but_simple_passwords -m pytest
    - name: Create report
      run: coverage xml
    - name: Upload report
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
